### ISSUE TITLE
ist eine 5er Version geplant?

### ISSUE THREAD

**Issue by skerbis** [TobiasKrais/d2u_kurse#1]

**Comment by TobiasKrais** [comment]
Voraussichtlich ja, Ende 2. Quartal 2018.

**Comment by TobiasKrais** [comment]
Neue Info: die Rex 5 Version wird voraussichtlich Anfang 2019 kommen.

**Comment by TobiasKrais** [comment]
Migration hat begonnen. Das Addon wird den Namen d2u_courses tragen: https://github.com/TobiasKrais/d2u_courses. Finanzierung ist gesucht!
